[workspace]
resolver = "2"

members = [
  "contracts/price-aggregator/interactor",
  "contracts/price-aggregator/meta",
  "contracts/potlock",
  "contracts/potlock/meta",
  "contracts/potlock/interact-rs",

]
